print("Welcome to the tip calculator!")
total_bill = float(input("Whats the total bill? "))
tip = float(input("How much tip would you like to give? 10, 12 , or 15?"))
persons = int(input("How many people to split the bill? "))
Each_person = round((total_bill + (total_bill * (tip/100))) / persons,2)
print(f"Each person should pay: {Each_person}")